[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@solady/contracts/=lib/solady/src/",
    "forge-std/=lib/forge-std/src/"
]

# Compiler settings
solc_version = "0.8.23"
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = false

# Test settings
verbosity = 2
fuzz_runs = 256

# Gas settings
gas_limit = 30000000
gas_price = 20000000000

# RPC endpoints
[rpc_endpoints]
base_mainnet = "${BASE_MAINNET_RPC_URL}"
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"
localhost = "http://localhost:8545"

# Etherscan multichain API keys
[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}", url = "https://api.etherscan.io/api" }
base = { key = "${ETHERSCAN_API_KEY}", url = "https://api.basescan.org/api" }
base_sepolia = { key = "${ETHERSCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api" }
polygon = { key = "${ETHERSCAN_API_KEY}", url = "https://api.polygonscan.com/api" }
arbitrum = { key = "${ETHERSCAN_API_KEY}", url = "https://api.arbiscan.io/api" }
optimism = { key = "${ETHERSCAN_API_KEY}", url = "https://api-optimistic.etherscan.io/api" }
